export const ROUTE_API_ERROR = 'ROUTE_API_ERROR'
export const STORE_ROUTES_INFO = 'STORE_ROUTES_INFO'

export const STORE_DIRECTIONS = 'STORE_DIRECTIONS'
export const DIRECTIONS_API_ERROR = 'DIRECTIONS_API_ERROR'

export const STORE_STOPS = 'STORE_STOPS'
export const STOPS_API_ERROR = 'STOPS_API_ERROR'

export const STORE_BUS_DETAILS = 'STORE_BUS_DETAILS'
export const BUS_DETAILS_API_ERROR = 'BUS_DETAILS_API_ERROR'

export const RESET_STOPS_INFO = 'RESET_STOPS_INFO'